<a href="https://colab.research.google.com/github/DrizzleAhuja/AIML/blob/main/Python-Codes-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [5]:

a = np.array([1, 2, 3, 4])



In [6]:
b = np.array([5, 6, 7, 8])

In [7]:
c = np.array([9, 10, 11, 12])

In [8]:
d = a+b+c

In [9]:
print(d)

[15 18 21 24]


In [10]:
d.sort()

In [11]:
d


array([15, 18, 21, 24])

In [12]:

e = np.array([(1, 2, 3), (4, 5, 6)], dtype=float)
print(e)

[[1. 2. 3.]
 [4. 5. 6.]]


In [13]:

e = np.array([(1, 2, 3), (4, 5, 6)], dtype=float)
print(e)

[[1. 2. 3.]
 [4. 5. 6.]]


In [14]:
g = np.zeros((3,3))

In [15]:
g


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:

e = np.array([(1, 2, 3), (4, 5, 6)], dtype=float)
print(e)

g = np.zeros((2, 3))  # Adjusted shape to match 'e'
s = e * g
print(s)


[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
h = np.ones((2,4))
h

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
i = np.arange(10,25,5)
i

array([10, 15, 20])

In [21]:
i

array([10, 15, 20])

In [22]:
j = np.linspace(0,2,9)

In [23]:
j

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [24]:
k  = np.full((2,2),7)
k

array([[7, 7],
       [7, 7]])

In [25]:
l = np.eye(2)
l

array([[1., 0.],
       [0., 1.]])

In [26]:
n = np.random.random((2,2))
n

array([[0.71152908, 0.74754439],
       [0.22784596, 0.82481526]])